---
---

# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway
  branch: sample
media_folder: "assets/uploads"
site_url: {{ site.url | prepend: site.baseurl }}
{% if site.logo %}
logo_url: {{ site.logo }}
{% endif %}
collections:
  - label: Posts
    label_singular: Post
    name: posts
    folder: _posts
    extension: md
    format: yaml-frontmatter
    create: true
    slug: {% raw %}"{{year}}-{{month}}-{{day}}-{{slug}}"{% endraw %}
    preview_page: {% raw %}"{{slug}}"{% endraw %}
    description: >
      The basic type of content.
    fields:
      - label: Title
        name: title
        widget: string
        default: New Post
        hint: Full title, used at the top of the page.
      - label: Publish Date
        name: date
        widget: datetime
        format: "YYYY-MM-DD HH:mm:ss ZZ"
      - label: Show on website
        name: published
        widget: boolean
        default: false
      - label: Body
        name: body
        widget: markdown
        default: New day, new post!
      - label: Post Image
        name: header
        widget: object
        hint: >
          The main image for the article. Will appear at the
          top of the body and will be featured in previews
          and thumbnails.
        fields:
          - label: Image
            name: image
            required: false
            widget: image
            allow_multiple: false
          - label: Width
            name: width
            required: false
            widget: number
            valueType: int
            hint: >
              The width, in pixels, of the uploaded image.
              This allows better loading on multiple devices.
          - label: Caption
            name: caption
            required: false
            widget: markdown
            buttons: [ bold, italic, link ]
  - label: Comments
    label_singular: Comment
    name: comments
    folder: _comments
    editor:
      preview: false
    extension: md
    format: yaml-frontmatter
    create: false
    identifier_field: replyTo
    description: >
      Comments appear here for moderation.
    fields:
      - label: Show on website
        name: published
        widget: boolean
        default: false
        hint: >
          Switch this to approve this comment
          and publish it to the website.
      - name: replyTo
        widget: hidden
      - label: Commenter
        name: name
        widget: string
      - label: Email
        name: email
        widget: string
      - label: Comment Date
        name: date
        widget: datetime
        format: "YYYY-MM-DD HH:mm:ss ZZ"
        timeFormat: false
      - label: Comment
        name: body
        widget: markdown
  - label: Data
    name: data
    editor:
      preview: false
    description: >
      This is where you will be able to update different
      types of data, which are used throughout the site.
    files:
      - label: Site Data
        name: site
        file: _config.yml
        fields:
          - label: Site title
            name: title
            widget: string
          - label: Site description
            name: description
            widget: string
          - label: Copyright
            name: copyright
            widget: object
            fields:
              - label: Copyright date
                name: date
                widget: datetime
                format: "YYYY-MM-DDTHH:mm:ssZ"
                hint: >
                  Usually the date the site was created,
                  unless otherwise renewed.
              - label: Site owner
                name: owner
                widget: string
          - label: Site image
            name: og_image
            required: false
            widget: image
            allow_multiple: false
          - label: Google Analytics
            name: google_analytics
            required: false
            widget: string
            hint: >
              Enter your tracking number to turn on analytics
              for the site.
      - label: Contact info
        name: contact
        file: _data/contact.yml
        fields: {% for c in site.data.icon-types %}
          - label: {{ c.label }}
            name: {{ c.type }}
            required: false
            widget: string {% endfor %}
